map_names = {"Mystery Zone", "Mystery Zone", "Mystery Zone", "Jubilife City", "Jubilife City", "Jubilife City",
             "Jubilife City", "Jubilife City", "Pokétch Co.", "Pokétch Co.", "Pokétch Co.", "Jubilife TV",
             "Jubilife TV", "Jubilife TV", "Jubilife TV", "Jubilife TV", "Jubilife TV", "Jubilife TV", "Jubilife TV",
             "Jubilife City", "Jubilife City", "Jubilife City", "Jubilife City", "Jubilife City", "Jubilife City",
             "Jubilife City", "Jubilife City", "Jubilife City", "Global Terminal", "Trainers’ School",
             "Jubilife City", "Jubilife City", "Jubilife City", "Canalave City", "Canalave City", "Canalave City",
             "Canalave City", "Canalave City", "Canalave Library", "Canalave Library", "Canalave Library",
             "Canalave City", "Canalave City", "Canalave City", "Canalave City", "Oreburgh City", "Oreburgh City",
             "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City",
             "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City",
             "Mining Museum", "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City", "Oreburgh City",
             "Eterna City", "Eterna City", "Eterna City", "Eterna City", "Eterna City", "Eterna City", "Cycle Shop",
             "T.G.Eterna Bldg", "T.G.Eterna Bldg", "T.G.Eterna Bldg", "T.G.Eterna Bldg", "Eterna City", "Eterna City",
             "Eterna City", "Eterna City", "Route 206", "Eterna City", "Eterna City", "Eterna City", "Eterna City",
             "Eterna City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City",
             "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City",
             "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City",
             "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City", "Hearthome City",
             "Route 208", "Route 209", "Route 212", "Hearthome City", "Hearthome City", "Hearthome City",
             "Hearthome City", "Poffin House", "Contest Hall", "Contest Hall", "Foreign Building", "Pastoria City",
             "Pastoria City", "Pastoria City", "Pastoria City", "Pastoria City", "Pastoria City", "Pastoria City",
             "Pastoria City", "Pastoria City", "Pastoria City", "Pastoria City", "Pastoria City", "Veilstone City",
             "Veilstone City", "Veilstone City", "Veilstone City", "Game Corner", "Veilstone Store", "Veilstone Store",
             "Veilstone Store", "Veilstone Store", "Veilstone Store", "Veilstone Store", "Veilstone City",
             "Veilstone City", "Veilstone City", "Veilstone City", "Veilstone City", "Veilstone City", "Route 215",
             "Sunyshore City", "Sunyshore City", "Sunyshore City", "Sunyshore City", "Sunyshore City", "Sunyshore City",
             "Sunyshore City", "Sunyshore Market", "Sunyshore City", "Sunyshore City", "Sunyshore City",
             "Sunyshore City", "Sunyshore City", "Sunyshore City", "Vista Lighthouse", "Snowpoint City",
             "Snowpoint City", "Snowpoint City", "Snowpoint City", "Snowpoint City", "Snowpoint City", "Snowpoint City",
             "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League",
             "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League",
             "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League",
             "Pokémon League", "Fight Area", "Fight Area", "Fight Area", "Fight Area", "Battle Park", "Route 225",
             "Fight Area", "Fight Area", "Mystery Zone", "Oreburgh Mine", "Oreburgh Mine", "Oreburgh Mine",
             "Valley Windworks", "Valley Windworks", "Eterna Forest", "Eterna Forest", "Fuego Ironworks",
             "Fuego Ironworks", "Mystery Zone", "Mt.Coronet", "Mt.Coronet", "Mt.Coronet", "Mt.Coronet", "Mt.Coronet",
             "Mt.Coronet", "Mt.Coronet", "Mt.Coronet", "Mt.Coronet", "Mt.Coronet", "Mt.Coronet", "Mt.Coronet",
             "Mt.Coronet", "Spear Pillar", "Spear Pillar", "Mystery Zone", "Pastoria City", "Mystery Zone",
             "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins",
             "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins",
             "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins", "Solaceon Ruins",
             "Mystery Zone", "Victory Road", "Victory Road", "Victory Road", "Victory Road", "Victory Road",
             "Victory Road", "Mystery Zone", "Pal Park", "Mystery Zone", "Amity Square", "Ravaged Path", "Mystery Zone",
             "Floaroma Meadow", "Floaroma Meadow", "Oreburgh Gate", "Oreburgh Gate", "Fullmoon Island",
             "Fullmoon Island", "Stark Mountain", "Stark Mountain", "Stark Mountain", "Stark Mountain", "Mystery Zone",
             "Sendoff Spring", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Turnback Cave", "Flower Paradise", "Mystery Zone", "Mystery Zone", "Mystery Zone", "Snowpoint Temple",
             "Snowpoint Temple", "Snowpoint Temple", "Snowpoint Temple", "Snowpoint Temple", "Snowpoint Temple",
             "Wayward Cave", "Wayward Cave", "Ruin Maniac Cave", "Trophy Garden", "Iron Island", "Iron Island",
             "Iron Island", "Iron Island", "Iron Island", "Iron Island", "Iron Island", "Old Chateau", "Old Chateau",
             "Old Chateau", "Old Chateau", "Old Chateau", "Old Chateau", "Old Chateau", "Old Chateau", "Old Chateau",
             "Mystery Zone", "Galactic HQ", "Galactic HQ", "Galactic HQ", "Galactic HQ", "Galactic HQ", "Galactic HQ",
             "Lake Verity", "Lake Verity", "Verity Cavern", "Lake Valor", "Lake Valor", "Valor Cavern", "Lake Acuity",
             "Lake Acuity", "Acuity Cavern", "Newmoon Island", "Newmoon Island", "Battle Park", "Battle Park",
             "Mystery Zone", "Mystery Zone", "Battle Tower", "Battle Tower", "Battle Tower", "Battle Tower",
             "Battle Tower", "Battle Tower", "Mystery Zone", "Mystery Zone", "Verity Lakefront", "Verity Lakefront",
             "Valor Lakefront", "Restaurant", "Grand Lake", "Grand Lake", "Acuity Lakefront", "Spring Path",
             "Route 201", "Route 202", "Route 203", "Route 204", "Route 204", "Route 205", "Route 205", "Route 205",
             "Route 206", "Route 206", "Mystery Zone", "Route 207", "Route 208", "Route 208", "Route 209", "Route 209",
             "Route 209", "Route 209", "Route 209", "Route 209", "Route 210", "Route 210", "Route 210", "Route 211",
             "Route 211", "Route 212", "Pokémon Mansion", "Pokémon Mansion", "Pokémon Mansion", "Route 212",
             "Route 212", "Route 213", "Route 213", "Footstep House", "Grand Lake", "Grand Lake", "Grand Lake",
             "Grand Lake", "Route 214", "Route 214", "Route 215", "Route 216", "Route 216", "Route 217", "Route 217",
             "Route 217", "Route 218", "Route 218", "Route 218", "Route 219", "Route 221", "Pal Park", "Route 221",
             "Route 222", "Route 222", "Route 222", "Route 222", "Route 224", "Route 225", "Mystery Zone",
             "Mystery Zone", "Route 227", "Mystery Zone", "Mystery Zone", "Route 228", "Route 229", "Mystery Zone",
             "Mystery Zone", "Mystery Zone", "Twinleaf Town", "Twinleaf Town", "Twinleaf Town", "Twinleaf Town",
             "Twinleaf Town", "Twinleaf Town", "Twinleaf Town", "Sandgem Town", "Sandgem Town", "Sandgem Town",
             "Sandgem Town", "Sandgem Town", "Sandgem Town", "Sandgem Town", "Sandgem Town", "Floaroma Town",
             "Floaroma Town", "Floaroma Town", "Floaroma Town", "Flower Shop", "Floaroma Town", "Floaroma Town",
             "Solaceon Town", "Solaceon Town", "Solaceon Town", "Solaceon Town", "Pokémon Day Care", "Solaceon Town",
             "Solaceon Town", "Solaceon Town", "Solaceon Town", "Celestic Town", "Celestic Town", "Celestic Town",
             "Celestic Town", "Celestic Town", "Celestic Town", "Celestic Town", "Celestic Town", "Survival Area",
             "Survival Area", "Survival Area", "Survival Area", "Battleground", "Survival Area", "Survival Area",
             "Resort Area", "Resort Area", "Resort Area", "Resort Area", "Resort Area", "Resort Area", "Resort Area",
             "Villa", "Resort Area", "Mystery Zone", "Route 220", "Route 223", "Route 226", "Mystery Zone", "Route 230",
             "Seabreak Path", "Mystery Zone", "Jubilife City", "Canalave City", "Oreburgh City", "Eterna City",
             "Hearthome City", "Pastoria City", "Veilstone City", "Sunyshore City", "Snowpoint City", "Pokémon League",
             "Fight Area", "Sandgem Town", "Floaroma Town", "Solaceon Town", "Celestic Town", "Survival Area",
             "Resort Area", "Canalave City", "Café", "Battle Tower", "Galactic HQ", "Pokémon League",
             "Pokémon League", "Galactic HQ", "Route 225", "Route 226", "Route 227", "Route 228", "Route 228",
             "Route 228", "Great Marsh", "Great Marsh", "Great Marsh", "Great Marsh", "Great Marsh", "Great Marsh",
             "Hall of Origin", "Hall of Origin", "Ruin Maniac Cave", "Maniac Tunnel", "Iron Island", "Solaceon Ruins",
             "Vista Lighthouse", "Jubilife City", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave", "Turnback Cave",
             "Contest Hall", "Battle Frontier", "Battle Frontier", "Battle Tower", "Battle Factory", "Battle Hall",
             "Battle Castle", "Battle Arcade", "Veilstone Store", "Global Terminal", "Global Terminal", "Galactic HQ",
             "Distortion World", "ROTOM’ s Room", "T.G.Eterna Bldg", "Distortion World", "Distortion World",
             "Distortion World", "Distortion World", "Distortion World", "Distortion World", "Distortion World",
             "Distortion World", "Distortion World", "Distortion World", "Distortion World", "Spear Pillar",
             "Spear Pillar", "Jubilife City", "Iron Island", "Iron Ruins", "Mt.Coronet", "Iceberg Ruins", "Route 228",
             "Rock Peak Ruins"}

if _ROM.version == "D" or _ROM.version == "P" then
    map_names[29] = "GTS"
    map_names[73] = "Eterna City"
    map_names[74] = "Eterna City"
    map_names[75] = "Eterna City"
    map_names[76] = "Eterna City"
    map_names[455] = "Survival Area"
    map_names[465] = "Resort Area"
end
