map_names = {"Black City", "Black City", "Black City", "Black City", "Black City", "Black City", "Striaton City",
             "Striaton City", "Striaton City", "Striaton City", "Striaton City", "Striaton City", "Striaton City",
             "Striaton City", "Striaton City", "Striaton City", "Nacrene City", "Nacrene City", "Nacrene City",
             "Nacrene City", "Nacrene City", "Nacrene City", "Nacrene City", "Nacrene City", "Nacrene City",
             "Nacrene City", "Nacrene City", "Nacrene Gate", "Castelia City", "Castelia City", "Castelia City",
             "Castelia City", "Castelia City", "Castelia City", "Castelia City", "Castelia City", "Castelia City",
             "Castelia City", "Castelia City", "Castelia City", "Castelia City", "Castelia City", "Castelia City",
             "Castelia City", "Castelia City", "Castelia City", "Castelia City", "Castelia City", "Castelia City",
             "Castelia City", "Castelia City", "Castelia Gate", "Royal Unova", "Castelia City", "Castelia City",
             "Castelia City", "Castelia City", "Medal Office", "Castelia City", "Castelia City", "Castelia City",
             "Castelia City", "Nimbasa City", "Nimbasa City", "Nimbasa City", "Nimbasa City", "Gear Station",
             "Gear Station", "Gear Station", "Gear Station", "Gear Station", "Gear Station", "Gear Station",
             "Gear Station", "Gear Station", "Battle Subway", "Battle Subway", "Musical Theater", "Musical Theater",
             "Nimbasa City", "Nimbasa City", "Nimbasa City", "Nimbasa City", "Nimbasa City", "Nimbasa City",
             "Nimbasa City", "Nimbasa City", "Nimbasa City", "Nimbasa City", "Nimbasa City", "Nimbasa Gate",
             "Nimbasa Gate", "Nimbasa Gate", "Nimbasa City", "Nimbasa City", "Nimbasa City", "Driftveil City",
             "Driftveil City", "Driftveil City", "Driftveil City", "Driftveil City", "Driftveil City", "Driftveil City",
             "Driftveil City", "Driftveil City", "Driftveil City", "Driftveil City", "Mistralton City",
             "Mistralton City", "Mistralton City", "Mistralton City", "Mistralton City", "Mistralton City",
             "Icirrus City", "Icirrus City", "Icirrus City", "Icirrus City", "Icirrus City", "Icirrus City",
             "Icirrus City", "Opelucid City", "Opelucid City", "Opelucid City", "Opelucid City", "Opelucid City",
             "Opelucid City", "Opelucid City", "Opelucid City", "Opelucid City", "Opelucid City", "Opelucid City",
             "Opelucid Gate", "Opelucid Gate", "Opelucid Gate", "Opelucid City", "Opelucid City", "Pokémon League",
             "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League",
             "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League",
             "Unity Tower", "Unity Tower", "Unity Tower", "－－－－－－－－－－",
             "－－－－－－－－－－", "Dreamyard", "Dreamyard", "Pinwheel Forest", "Pinwheel Forest",
             "Rumination Field", "Desert Resort", "Desert Resort", "Route Gate", "Relic Castle", "Relic Castle",
             "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle",
             "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle",
             "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle",
             "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle",
             "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "Relic Castle", "PWT", "PWT", "PWT",
             "Chargestone Cave", "Chargestone Cave", "Chargestone Cave", "Chargestone Cave", "Twist Mountain",
             "Twist Mountain", "Twist Mountain", "Twist Mountain", "Twist Mountain", "Twist Mountain", "Twist Mountain",
             "Dragonspiral Tower", "Dragonspiral Tower", "Dragonspiral Tower", "Dragonspiral Tower",
             "Dragonspiral Tower", "Dragonspiral Tower", "Dragonspiral Tower", "Dragonspiral Tower",
             "Dragonspiral Tower", "Victory Road", "Victory Road", "Victory Road", "Victory Road", "Victory Road",
             "Victory Road", "Victory Road", "Victory Road", "Victory Road", "Victory Road", "Victory Road",
             "Victory Road", "Victory Road", "Victory Road", "Victory Road", "Trial Chamber", "Giant Chasm",
             "Giant Chasm", "Giant Chasm", "Giant Chasm", "Giant Chasm", "Liberty Garden", "Liberty Garden",
             "Liberty Garden", "P2 Laboratory", "P2 Laboratory", "Undella Bay", "Abyssal Ruins", "Abyssal Ruins",
             "Abyssal Ruins", "Abyssal Ruins", "Abyssal Ruins", "Abyssal Ruins", "Abyssal Ruins", "Abyssal Ruins",
             "Skyarrow Bridge", "Bridge Gate", "Bridge Gate", "Bridge Gate", "Driftveil Drawbridge", "Tubeline Bridge",
             "Village Bridge", "Village Bridge", "Village Bridge", "Village Bridge", "Village Bridge", "Village Bridge",
             "Village Bridge", "Village Bridge", "Marvelous Bridge", "N's Castle", "N's Castle", "N's Castle",
             "N's Castle", "N's Castle", "N's Castle", "N's Castle", "N's Castle", "N's Castle", "N's Castle",
             "N's Castle", "N's Castle", "N's Castle", "N's Castle", "N's Castle", "Entralink", "Entree Forest",
             "Entree Forest", "Entree Forest", "Entree Forest", "Entree Forest", "Entree Forest", "Entree Forest",
             "Entree Forest", "Entree Forest", "Nimbasa City", "Driftveil City", "Mistralton City", "Icirrus City",
             "Opelucid City", "Black City", "White Forest", "Cold Storage", "Chargestone Cave", "Twist Mountain",
             "Dragonspiral Tower", "Giant Chasm", "Driftveil Drawbridge", "Tubeline Bridge", "Marvelous Bridge",
             "Route 5", "Route 6", "Route 7", "Route 8", "Route 9", "Route 11", "Route 12", "Route 13", "Route 14",
             "Route 15", "Route 16", "Lacunosa Town", "Undella Town", "Route 1", "Route Gate", "Route 2",
             "Accumula Gate", "Route 3", "Route 3", "Route 3", "Wellspring Cave", "Wellspring Cave", "Route 4",
             "Route 4", "Route 4", "Route 5", "Route 5", "Route 6", "Route 6", "Mistralton Cave", "Mistralton Cave",
             "Guidance Chamber", "Route 6", "Route 7", "Celestial Tower", "Celestial Tower", "Celestial Tower",
             "Celestial Tower", "Celestial Tower", "Route 7", "Route 7", "Route 8", "Moor of Icirrus", "Bridge Gate",
             "Route 9", "Bridge Gate", "Shopping Mall", "Shopping Mall", "Challenger's Cave", "Challenger's Cave",
             "Challenger's Cave", "Route 10", "Route 10", "Route 10", "Route 10", "Route 10", "Route 10", "Route 10",
             "Route 10", "Route 10", "Route 10", "Route 11", "Bridge Gate", "Route 11", "Route 12", "Bridge Gate",
             "Route 13", "Route 13", "Undella Gate", "Route 13", "Route 14", "Black Gate", "Abundant Shrine",
             "Abundant Shrine", "Route 15", "Black Gate", "Bridge Gate", "Poké Transfer Lab", "Route 15", "Route 16",
             "Bridge Gate", "Lostlorn Forest", "Lostlorn Forest", "Route 18", "Route 18", "Nuvema Town", "Nuvema Town",
             "Nuvema Town", "Nuvema Town", "Nuvema Town", "Nuvema Town", "Nuvema Town", "Nuvema Town", "Accumula Town",
             "Accumula Town", "Accumula Town", "Accumula Town", "Accumula Town", "Accumula Town", "Accumula Town",
             "Accumula Town", "Accumula Town", "Lacunosa Town", "Lacunosa Town", "Lacunosa Town", "Lacunosa Town",
             "Lacunosa Town", "Lacunosa Town", "Undella Town", "Undella Town", "Bridge Gate", "Undella Town",
             "Undella Town", "Undella Town", "Anville Town", "Anville Town", "Anville Town", "Anville Town",
             "－－－－－－－－－－", "Route 17", "White Forest", "White Forest", "White Forest",
             "Aspertia City", "Aspertia City", "Aspertia City", "Aspertia City", "Aspertia City", "Aspertia City",
             "Aspertia City", "Aspertia City", "Aspertia City", "Aspertia City", "Route 19", "Aspertia Gate",
             "Floccesy Town", "Floccesy Town", "Floccesy Town", "Floccesy Town", "Floccesy Town", "Floccesy Ranch",
             "Floccesy Ranch", "Route 20", "Virbank Gate", "Virbank City", "Virbank City", "Virbank City",
             "Virbank City", "Virbank City", "Virbank Gate", "Virbank City", "Virbank City", "Virbank Complex",
             "Virbank Complex", "Lentimas Town", "Lentimas Town", "Lentimas Town", "Reversal Mountain", "Strange House",
             "Route 21", "Marine Tube", "Humilau City", "Humilau City", "Humilau City", "Humilau City", "Humilau City",
             "Humilau City", "Bridge Gate", "Humilau City", "Humilau City", "Route 22", "Route 23", "Route 23",
             "Route 23", "White Treehollow", "Black Tower", "White Treehollow", "Black Tower", "White Treehollow",
             "Black Tower", "Black Tower", "White Treehollow", "Black Tower", "White Treehollow", "Castelia City",
             "Aspertia City", "Join Avenue", "Join Avenue", "White Treehollow", "Black Tower", "Castelia City",
             "Castelia Sewers", "Castelia Sewers", "Castelia Sewers", "Castelia Sewers", "Castelia Sewers",
             "Castelia City", "Castelia City", "Virbank City", "Relic Passage", "Relic Passage", "Relic Passage",
             "Clay Tunnel", "Clay Tunnel", "Clay Tunnel", "Twist Mountain", "Strange House", "Strange House",
             "Strange House", "Strange House", "Strange House", "Seaside Cave", "Seaside Cave", "Cave of Being",
             "Hidden Grotto", "Route 4", "Route 4", "Route 4", "Route 4", "Route 4", "Route 4", "Route 4", "Route 4",
             "Route 4", "Route 4", "Route 4", "Route 4", "Reversal Mountain", "Reversal Mountain", "Reversal Mountain",
             "Reversal Mountain", "Reversal Mountain", "Reversal Mountain", "Reversal Mountain", "Reversal Mountain",
             "Reversal Mountain", "Reversal Mountain", "Reversal Mountain", "Reversal Mountain", "Driftveil City",
             "Driftveil City", "Driftveil City", "Driftveil City", "Driftveil City", "Driftveil City", "Driftveil City",
             "Driftveil City", "Route 4", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate",
             "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate",
             "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Underground Ruins", "Pokéstar Studios",
             "Pokéstar Studios", "Pokéstar Studios", "Strange House", "Strange House", "Strange House",
             "Strange House", "Victory Road", "Pokéstar Studios", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate",
             "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate", "Plasma Frigate",
             "Nature Preserve", "Nimbasa City", "Pokéstar Studios", "Victory Road", "Victory Road", "Victory Road",
             "Victory Road", "Victory Road", "Victory Road", "Victory Road", "Victory Road", "Victory Road",
             "Victory Road", "Striaton City", "Nacrene City", "Undella Town", "Floccesy Town", "Opelucid City",
             "Victory Road", "Driftveil City", "Giant Chasm", "Village Bridge", "Musical Theater", "Chargestone Cave",
             "Lentimas Town", "Underground Ruins", "Underground Ruins", "Rock Peak Chamber", "Iceberg Chamber",
             "Iron Chamber", "Pledge Grove"}

if _ROM.version == "B" or _ROM.version == "W" then
    map_names[58] = "Castelia City"
    map_names[192] = "Cold Storage"
    map_names[193] = "Cold Storage"
    map_names[194] = "Cold Storage"
    map_names[415] = "Undella Town"
end
