map_names = {"Mystery Zone", "Mystery Zone", "Mystery Zone", "Mystery Zone", "Mystery Zone", "Mystery Zone",
             "Bellchime Trail", "Burned Tower", "Ruins of Alph", "Route 1", "Route 2", "Route 3", "Route 4", "Route 5",
             "Route 6", "Route 7", "Route 8", "Route 9", "Route 10", "Route 11", "Route 12", "Route 13", "Route 14",
             "Route 15", "Route 16", "Route 17", "Route 18", "Route 22", "Route 24", "Route 25", "Route 26", "Route 27",
             "Route 28", "Route 29", "Route 30", "Route 31", "Route 32", "Route 33", "Route 34", "Route 35", "Route 36",
             "Route 37", "Route 38", "Route 39", "Route 42", "Route 43", "Route 44", "Route 45", "Route 46",
             "Pallet Town", "Viridian City", "Pewter City", "Cerulean City", "Lavender Town", "Vermilion City",
             "Celadon City", "Fuchsia City", "Cinnabar Island", "Indigo Plateau", "Saffron City", "New Bark Town",
             "New Bark Town", "New Bark Town", "New Bark Town", "New Bark Town", "New Bark Town", "New Bark Town",
             "Cherrygrove City", "Cherrygrove City", "Cherrygrove City", "Cherrygrove City", "Cherrygrove City",
             "Cherrygrove City", "Violet City", "Azalea Town", "Cianwood City", "Goldenrod City", "Olivine City",
             "Ecruteak City", "Ecruteak City", "Ecruteak City", "Ecruteak City", "Jubilife City", "Ecruteak City",
             "Ecruteak City", "Ecruteak City", "Ecruteak City", "Mahogany Town", "Lake of Rage", "Blackthorn City",
             "Mt. Silver", "Route 19", "Route 20", "Route 21", "Route 40", "Route 41", "National Park", "Route 31",
             "Route 32", "Union Cave", "Azalea Town", "Route 35", "Route 35", "Route 36", "Route 36", "Jubilife City",
             "DIGLETT’s Cave", "Mt. Moon", "Rock Tunnel", "Pal Park", "Sprout Tower", "Bell Tower", "Radio Tower",
             "Ruins of Alph", "SLOWPOKE Well", "Lighthouse", "Mahogany Town", "Ilex Forest", "Goldenrod Tunnel",
             "Mt. Mortar", "Ice Path", "Whirl Islands", "Mt. Silver Cave", "Dark Cave", "Victory Road",
             "Dragon’s Den", "Tohjo Falls", "Route 30", "Ecruteak City", "Ecruteak City", "Ecruteak City",
             "Ecruteak City", "Route 42", "Mahogany Town", "Route 29", "Violet City", "Azalea Town", "Goldenrod City",
             "Olivine City", "Cianwood City", "Mahogany Town", "Blackthorn City", "Route 43", "Route 30",
             "Cherrygrove City", "Cerulean Cave", "Seafoam Islands", "Viridian Forest", "Power Plant", "Route 36",
             "Pokéathlon Dome", "Route 47", "Route 48", "Union Cave", "Union Cave", "Sprout Tower", "Sprout Tower",
             "Violet City", "Violet City", "Violet City", "Violet City", "Jubilife City", "Violet City", "Azalea Town",
             "Azalea Town", "Azalea Town", "Azalea Town", "Violet City", "Azalea Town", "Route 32", "Route 32",
             "Route 34", "Route 38", "Safari Zone Gate", "Safari Zone Gate", "Jubilife City", "Dark Cave",
             "SLOWPOKE Well", "Victory Road", "Victory Road", "Azalea Town", "SLOWPOKE Well", "Goldenrod City",
             "Goldenrod City", "Goldenrod City", "Goldenrod City", "Radio Tower", "Radio Tower", "Radio Tower",
             "Radio Tower", "Radio Tower", "Goldenrod City", "Goldenrod City", "Goldenrod City", "Goldenrod City",
             "Goldenrod City", "Goldenrod City", "Goldenrod City", "Goldenrod City", "Goldenrod Tunnel",
             "Goldenrod City", "Goldenrod City", "Goldenrod City", "Goldenrod City", "Goldenrod City", "Goldenrod City",
             "Goldenrod City", "Global Terminal", "Goldenrod City", "Goldenrod City", "Goldenrod City",
             "Goldenrod City", "Goldenrod City", "Goldenrod City", "Route 39", "Route 39", "Ecruteak City",
             "Burned Tower", "Ruins of Alph", "Goldenrod City", "Lighthouse", "Lighthouse", "Lighthouse", "Lighthouse",
             "Lighthouse", "Lighthouse", "Olivine City", "Olivine City", "Olivine City", "Olivine City", "Olivine City",
             "Olivine City", "Cianwood City", "Cianwood City", "Cianwood City", "Cianwood City", "Cianwood City",
             "Ice Path", "Ice Path", "Ice Path", "Olivine City", "Cianwood City", "Whirl Islands", "Whirl Islands",
             "Whirl Islands", "Route 43", "Mahogany Town", "Team Rocket HQ", "Team Rocket HQ", "Team Rocket HQ",
             "Mt. Mortar", "Mt. Mortar", "Mt. Mortar", "Dragon’s Den", "Fight Area", "Fight Area", "Fight Area",
             "Fight Area", "Fight Area", "Fight Area", "Fight Area", "Fight Area", "Fight Area", "Battle Park",
             "Battle Park", "Battle Tower", "Battle Tower", "Battle Tower", "Battle Tower", "Battle Tower",
             "Battle Tower", "Battle Tower", "Battle Frontier", "Battle Frontier", "Battle Tower", "Battle Factory",
             "Battle Hall", "Battle Castle", "Battle Arcade", "Cliff Edge Gate", "Pokéathlon Dome", "Pokéathlon Dome",
             "Pokéathlon Dome", "Pokéathlon Dome", "Pokéathlon Dome", "Pokéathlon Dome", "Pokéathlon Dome",
             "Pokéathlon Dome", "Dragon’s Den", "Blackthorn City", "Blackthorn City", "Blackthorn City",
             "Blackthorn City", "Blackthorn City", "Lake of Rage", "Lake of Rage", "Route 26", "Route 26",
             "Tohjo Falls", "Route 26", "Pokémon League", "Pokémon League", "Pokémon League", "Pokémon League",
             "Pokémon League", "Pokémon League", "Pokémon League", "S.S. Aqua", "S.S. Aqua", "S.S. Aqua",
             "S.S. Aqua", "S.S. Aqua", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph",
             "Ruins of Alph", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph",
             "Route 27", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph",
             "S.S. Aqua", "S.S. Aqua", "Olivine City", "Route 34", "Bell Tower", "Bell Tower", "Bell Tower",
             "Bell Tower", "Bell Tower", "Bell Tower", "Bell Tower", "Bell Tower", "Bell Tower", "Bell Tower",
             "Cliff Cave", "Safari Zone", "Safari Zone", "Safari Zone", "Safari Zone", "Safari Zone", "Safari Zone",
             "Safari Zone", "Safari Zone", "Safari Zone", "Safari Zone", "Safari Zone", "Safari Zone", "Safari Zone",
             "Safari Zone", "Safari Zone", "Vermilion City", "Vermilion City", "Vermilion City", "Vermilion City",
             "Vermilion City", "Vermilion City", "Vermilion City", "Vermilion City", "Route 40", "Olivine City",
             "Mahogany Town", "Blackthorn City", "Celadon City", "Celadon City", "Celadon City", "Celadon City",
             "Celadon City", "Celadon City", "Celadon City", "Celadon City", "Celadon City", "Celadon City",
             "Celadon City", "Celadon City", "Celadon City", "Celadon City", "New Bark Town", "Cianwood City",
             "Vermilion City", "Vermilion City", "Route 10", "Route 6", "Route 8", "Route 5", "Route 15",
             "Celadon City", "Celadon City", "Celadon City", "Mahogany Town", "Mahogany Town", "Saffron City",
             "Saffron City", "Saffron City", "Saffron City", "Saffron City", "ROTOM’s Room", "Saffron City",
             "Saffron City", "Saffron City", "Saffron City", "Saffron City", "Saffron City", "Saffron City",
             "Frontier Access", "Global Terminal", "Global Terminal", "Route 2", "Route 16", "Route 20", "Route 2",
             "Route 2", "Route 2", "Route 2", "Route 16", "Route 16", "Route 18", "Route 19", "Route 11",
             "Cerulean City", "Cerulean City", "Cerulean City", "Cerulean City", "Cerulean City", "Cerulean City",
             "Cerulean City", "Lavender Town", "Lavender Town", "Lavender Town", "Lavender Town", "Lavender Town",
             "Lavender Town", "Lavender Town", "Route 25", "Goldenrod City", "Celadon City", "Celadon City",
             "Celadon City", "Saffron City", "Lighthouse", "Radio Tower", "Mt. Moon", "Mt. Moon", "Cerulean Cave",
             "Cerulean Cave", "Rock Tunnel", "Seafoam Islands", "Seafoam Islands", "Seafoam Islands", "Seafoam Islands",
             "Seafoam Islands", "Seafoam Islands", "Mt. Silver Cave", "Mt. Silver Cave", "Mt. Silver Cave",
             "Mt. Silver Cave", "Mt. Silver Cave", "Mt. Silver Cave", "Mt. Silver Cave", "Route 10", "Power Plant",
             "Route 5", "Route 5", "Route 6", "Pewter City", "Pewter City", "Pewter City", "Pewter City", "Pewter City",
             "Pewter City", "Pewter City", "Fuchsia City", "Pal Park", "Fuchsia City", "Fuchsia City", "Fuchsia City",
             "Fuchsia City", "Route 10", "Fuchsia City", "Whirl Islands", "National Park", "National Park",
             "Power Plant", "Ruins of Alph", "Ruins of Alph", "Ruins of Alph", "Route 7", "Lavender Town",
             "Cerulean City", "Viridian City", "Viridian City", "Viridian City", "Viridian City", "Viridian City",
             "Viridian City", "Viridian City", "Pallet Town", "Pallet Town", "Pallet Town", "Pallet Town",
             "Pallet Town", "Cinnabar Island", "Cinnabar Island", "Route 28", "Route 3", "Route 3", "Mt. Moon",
             "Mt. Silver", "Mt. Silver", "Mystery Zone", "Route 5", "Mt. Moon", "Goldenrod City", "Saffron City",
             "Sinjoh Ruins", "Sinjoh Ruins", "Sinjoh Ruins", "Embedded Tower", "Embedded Tower", "Embedded Tower",
             "Route 1", "Frontier Access", "Frontier Access", "Frontier Access", "Frontier Access", "Route 5",
             "Route 12", "Safari Zone Gate", "Safari Zone Gate", "Goldenrod City", "Celadon City", "Mystery Zone",
             "Pokémon League"}
